language: go
sudo: false
go:
- 1.13.1  
before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint
script:
- golangci-lint run
- go test -v -race ./...
- go test -v -covermode=count -coverprofile=profile.cov
- $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci
